#!/bin/bash 

[ -f "/etc/os-release" ] && source /etc/os-release

if [ "$(id -u)" != 0 ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ "$ID" != "gentoo" ]; then
	echo "This script is Gentoo specific" 1>&2
	exit 1
fi

type parallel || emerge sys-process/parallel

qlist -Iv | parallel -j $(nproc) equery k -o {}

